import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Download, FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";

interface ReportGeneratorProps {
  analysisData: any;
  eventType?: string;
  region?: string;
}

const ReportGenerator = ({ analysisData, eventType, region }: ReportGeneratorProps) => {
  const [reportType, setReportType] = useState<"professional" | "simple">("simple");
  const [isGenerating, setIsGenerating] = useState(false);

  const generateReport = async () => {
    if (!analysisData) {
      toast.error("No analysis data available");
      return;
    }

    setIsGenerating(true);

    try {
      const isSimple = reportType === "simple";
      const date = new Date().toLocaleString();

      let report = "";

      if (isSimple) {
        report = `
═══════════════════════════════════════════════════════════
         GEOPULSE ENVIRONMENTAL ANALYSIS REPORT
               Simple Summary Version
═══════════════════════════════════════════════════════════

📅 Date: ${date}
📍 Location: ${region || analysisData.region || "Africa"}
🔍 Event Type: ${eventType || analysisData.eventType || "Environmental Analysis"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 WHAT WE FOUND
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${analysisData.summary || "Analysis complete. Please review the detailed findings below."}

📈 Change Detected: ${analysisData.changePercent || analysisData.change_percent || "N/A"}%
📐 Area Analyzed: ${analysisData.area || analysisData.area_analyzed || "N/A"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 KEY POINTS (Easy to Understand)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${(analysisData.findings || analysisData.recommendations || [])
  .map((item: string, i: number) => `  ${i + 1}. ${item}`)
  .join("\n") || "  • Environmental changes detected in the analyzed area"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 WHAT THIS MEANS FOR YOU
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This report shows environmental changes in your area of interest.
The changes detected may affect local ecosystems, agriculture,
and communities. Consider sharing this report with local authorities
or environmental organizations for further action.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🌍 Report generated by GeoPulse AI
   www.geopulse.app
═══════════════════════════════════════════════════════════
        `.trim();
      } else {
        // Professional Report
        report = `
╔═══════════════════════════════════════════════════════════════════════════╗
║                    GEOPULSE ENVIRONMENTAL ANALYSIS                        ║
║                      Professional Technical Report                        ║
╚═══════════════════════════════════════════════════════════════════════════╝

DOCUMENT CLASSIFICATION: Environmental Assessment Report
REPORT ID: GP-${Date.now().toString(36).toUpperCase()}
GENERATION DATE: ${date}
ANALYSIS FRAMEWORK: GeoPulse AI v2.0

═══════════════════════════════════════════════════════════════════════════

1. EXECUTIVE SUMMARY
─────────────────────────────────────────────────────────────────────────────

Region of Analysis:     ${region || analysisData.region || "Specified African Region"}
Event Classification:   ${eventType || analysisData.eventType || "Environmental Change Detection"}
Analysis Period:        ${analysisData.startDate || "N/A"} to ${analysisData.endDate || "N/A"}
Confidence Index:       ${analysisData.confidenceLevel || 85}%
Severity Assessment:    ${analysisData.severity?.toUpperCase() || "MODERATE"}

${analysisData.summary || "Comprehensive environmental analysis completed for the specified parameters."}

═══════════════════════════════════════════════════════════════════════════

2. QUANTITATIVE METRICS
─────────────────────────────────────────────────────────────────────────────

  • Total Area Analyzed:        ${analysisData.area || analysisData.area_analyzed || "N/A"}
  • Percentage Change:          ${analysisData.changePercent || analysisData.change_percent || "N/A"}%
  • Geographic Coordinates:     ${analysisData.coordinates ? JSON.stringify(analysisData.coordinates) : "On file"}
  • Temporal Resolution:        Multi-temporal analysis
  • Spatial Resolution:         10-30m (Sentinel/Landsat derived)

═══════════════════════════════════════════════════════════════════════════

3. DETAILED TECHNICAL ANALYSIS
─────────────────────────────────────────────────────────────────────────────

${analysisData.fullAnalysis || analysisData.detailed_analysis || analysisData.detailedAnalysis || 
`The analysis utilized advanced remote sensing techniques to detect and 
quantify environmental changes within the specified region. Spectral 
indices including NDVI (Normalized Difference Vegetation Index), NDWI 
(Normalized Difference Water Index), and NBR (Normalized Burn Ratio) 
were computed to assess vegetation health, water presence, and burn 
severity respectively.

Change detection was performed using a combination of image differencing 
and machine learning classification algorithms, with validation against 
known reference data where available.`}

═══════════════════════════════════════════════════════════════════════════

4. KEY FINDINGS & OBSERVATIONS
─────────────────────────────────────────────────────────────────────────────

${(analysisData.findings || analysisData.recommendations || [])
  .map((item: string, i: number) => `  ${i + 1}. ${item}`)
  .join("\n\n") || `  1. Significant environmental changes detected within analysis period
  2. Spatial patterns indicate anthropogenic and natural drivers
  3. Temporal trends suggest ongoing environmental pressure`}

═══════════════════════════════════════════════════════════════════════════

5. METHODOLOGY & DATA SOURCES
─────────────────────────────────────────────────────────────────────────────

Data Sources:
${(analysisData.dataSources || ["Satellite imagery", "Environmental databases", "AI analysis"])
  .map((s: string) => `  • ${s}`)
  .join("\n")}

Analytical Methods:
  • Multi-spectral image analysis
  • Time-series change detection
  • Machine learning classification
  • Statistical trend analysis
  • AI-powered interpretation

Quality Assurance:
  • Cross-validation with multiple data sources
  • Confidence interval calculation
  • Uncertainty quantification

═══════════════════════════════════════════════════════════════════════════

6. RECOMMENDATIONS
─────────────────────────────────────────────────────────────────────────────

${(analysisData.recommendations || [])
  .map((rec: string, i: number) => `  ${i + 1}. ${rec}`)
  .join("\n\n") || `  1. Implement continuous monitoring protocols for the affected area
  2. Engage local stakeholders in environmental protection initiatives
  3. Consider detailed field validation of remote sensing findings
  4. Develop mitigation strategies based on observed trends`}

═══════════════════════════════════════════════════════════════════════════

7. DISCLAIMER & LIMITATIONS
─────────────────────────────────────────────────────────────────────────────

This report is generated using automated satellite image analysis and AI
interpretation. While every effort has been made to ensure accuracy, 
results should be validated through ground-truthing and expert review
before being used for critical decision-making.

Limitations:
  • Cloud cover may affect data availability
  • Spatial resolution limits fine-scale detection
  • AI interpretation subject to model training data

═══════════════════════════════════════════════════════════════════════════

REPORT GENERATED BY: GeoPulse AI Environmental Analysis System
CONTACT: support@geopulse.app
VERSION: 2.0.0

╔═══════════════════════════════════════════════════════════════════════════╗
║                    END OF PROFESSIONAL REPORT                             ║
╚═══════════════════════════════════════════════════════════════════════════╝
        `.trim();
      }

      // Create downloadable file
      const blob = new Blob([report], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `geopulse-${reportType}-report-${new Date().toISOString().split("T")[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success(`${reportType === "professional" ? "Professional" : "Simple"} report downloaded!`);
    } catch (error) {
      console.error("Report generation error:", error);
      toast.error("Failed to generate report");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-4">
      <div>
        <Label className="text-sm font-medium mb-2 block">Report Format</Label>
        <Select value={reportType} onValueChange={(v) => setReportType(v as "professional" | "simple")}>
          <SelectTrigger className="bg-card">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="simple">
              <span className="flex items-center gap-2">
                <span>📝</span> Simple - Easy to understand summary
              </span>
            </SelectItem>
            <SelectItem value="professional">
              <span className="flex items-center gap-2">
                <span>📊</span> Professional - Detailed technical report
              </span>
            </SelectItem>
          </SelectContent>
        </Select>
      </div>

      <Button
        className="w-full"
        variant="outline"
        onClick={generateReport}
        disabled={isGenerating || !analysisData}
      >
        {isGenerating ? (
          <>
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            Generating Report...
          </>
        ) : (
          <>
            <Download className="h-4 w-4 mr-2" />
            Download Report
          </>
        )}
      </Button>
    </div>
  );
};

export default ReportGenerator;
